/**
 * Telephony / IVR adapter — **the one documented audio exception** (see docs/privacy-notice.md).
 *
 * OFF unless `IVR_ENABLED=1`, so a default deploy answers `/api/health` with `audioRoutes: 0` and
 * this route 404s. When it is switched on, the contract is:
 *
 *   * a CPaaS provider (Twilio / Exotel / Plivo) does the speech-to-text on their side;
 *   * we receive the transcript of what the *caller read out*, run the same deterministic Tier-0
 *     core the browser runs, and answer with a spoken line;
 *   * we never receive or store audio, and we never persist the transcript — only the SHA-256 of the
 *     normalised text plus the evidence codes, exactly like the browser's shared-cache write;
 *   * the answer is never generated by a language model. It is a fixed line per rung, so it is
 *     auditable, translatable, and cannot hallucinate advice.
 *
 * Provider notes: `POST` accepts `application/x-www-form-urlencoded` in the Twilio/Exotel shape
 * (`SpeechResult`, `Digits`, `CallSid`, `From`) or JSON `{ text, lang, format }`. The response is
 * TwiML-compatible XML unless `Accept: application/json` (or `?format=json`) is asked for.
 */
import { runTier0 } from "@/core/fusion";
import { cleanSpokenInput, ivrXml, spokenVerdict, type IvrLang } from "@/core/ivr";
import { storeKind, putVerdict } from "@/server/store";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 10;

const MAX_INPUT = 1200;
const WINDOW_MS = 60_000;
const MAX_PER_WINDOW = 20;

/** per-caller counter, in memory only — the caller id is hashed, never stored raw */
const calls = new Map<string, { n: number; t: number }>();

function callerKey(req: Request, body: Record<string, string>): string {
  const raw = body.From || body.CallSid || req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "anon";
  let h = 2166136261;
  for (let i = 0; i < raw.length; i++) {
    h ^= raw.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(16);
}

function rateLimited(key: string): boolean {
  const now = Date.now();
  const c = calls.get(key);
  if (c && now - c.t < WINDOW_MS) {
    if (c.n >= MAX_PER_WINDOW) return true;
    c.n++;
    return false;
  }
  calls.set(key, { n: 1, t: now });
  // opportunistic cleanup so a long-lived instance cannot grow without bound
  if (calls.size > 5000) for (const [k, v] of calls) if (now - v.t > WINDOW_MS) calls.delete(k);
  return false;
}

function pickLang(body: Record<string, string>, url: URL): IvrLang {
  const v = (body.Language || body.lang || url.searchParams.get("lang") || "en").toLowerCase();
  return v.startsWith("hi") ? "hi" : "en";
}

async function readInput(req: Request): Promise<{ body: Record<string, string>; url: URL }> {
  const url = new URL(req.url);
  const ct = req.headers.get("content-type") || "";
  const body: Record<string, string> = {};
  if (ct.includes("application/json")) {
    const j = (await req.json().catch(() => ({}))) as Record<string, unknown>;
    for (const k of ["text", "SpeechResult", "Digits", "From", "CallSid", "Language", "lang"]) {
      if (j[k] !== undefined) body[k] = String(j[k]);
    }
  } else if (ct.includes("form")) {
    const f = await req.formData().catch(() => null);
    f?.forEach((v, k) => { body[k] = String(v); });
  } else {
    body.text = await req.text().catch(() => "");
  }
  return { body, url };
}

export async function POST(req: Request) {
  if (process.env.IVR_ENABLED !== "1") {
    // Not an error the caller should ever see: the route simply does not exist on a default deploy.
    return new Response("not enabled", { status: 404, headers: { "cache-control": "no-store" } });
  }

  const { body, url } = await readInput(req);
  const wantsJson = (req.headers.get("accept") || "").includes("application/json") || url.searchParams.get("format") === "json";
  const lang = pickLang(body, url);
  const text = cleanSpokenInput(body.SpeechResult || body.Digits || body.text || "", MAX_INPUT);

  const json = (payload: unknown, status = 200) =>
    new Response(JSON.stringify(payload), { status, headers: { "content-type": "application/json", "cache-control": "no-store", "x-robots-tag": "noindex" } });

  if (!text) {
    const empty = spokenVerdict({ rung: "unclear", score: 0, evidence: [] }, lang);
    empty.say = lang === "hi" ? "कृपया संदेश दोबारा बोलें।" : "Please say the message again.";
    return wantsJson ? json({ error: "empty", say: empty.say }) : new Response(ivrXml(empty, { lang }), { headers: { "content-type": "application/xml", "cache-control": "no-store", "x-robots-tag": "noindex" } });
  }

  const key = callerKey(req, body);
  if (rateLimited(key)) {
    const busy = spokenVerdict({ rung: "unclear", score: 0, evidence: [] }, lang);
    busy.say = lang === "hi" ? "अभी बहुत कॉल हैं। कृपया कुछ देर बाद प्रयास करें।" : "Too many calls right now. Please try again shortly.";
    return wantsJson ? json({ error: "rate limited" }, 429) : new Response(ivrXml(busy, { lang }), { status: 429, headers: { "content-type": "application/xml", "cache-control": "no-store" } });
  }

  const t0 = await runTier0(text);
  const line = spokenVerdict(t0, lang);

  // Hash + codes only — the same record the browser writes, never the transcript. Failure to write
  // must never break the call, so this is best-effort and the phone gets its answer either way.
  putVerdict({
    hash: t0.hash,
    simhash: t0.simhash,
    rung: t0.rung,
    codes: line.codes,
    modelVersion: "tier0-ivr",
  }).catch(() => {});

  if (wantsJson) {
    return json({
      rung: line.rung,
      score: Number(line.score.toFixed(2)),
      uncertain: line.uncertain,
      say: line.say,
      codes: line.codes,
      store: storeKind,
      audioStored: false,
      transcriptStored: false,
    });
  }
  return new Response(ivrXml(line, { lang }), {
    headers: { "content-type": "application/xml", "cache-control": "no-store", "x-robots-tag": "noindex" },
  });
}

/** A GET is a health probe for the IVR path, not a way to query it. */
export async function GET() {
  return Response.json(
    {
      enabled: process.env.IVR_ENABLED === "1",
      contract: "transcript in (from your telephony provider) → deterministic Tier-0 verdict out",
      audioStored: false,
      transcriptStored: false,
      maxInputChars: MAX_INPUT,
      rateLimit: `${MAX_PER_WINDOW} calls/minute per caller`,
      languages: ["en", "hi"],
    },
    { headers: { "cache-control": "no-store", "x-robots-tag": "noindex" } },
  );
}
